openapi: 3.2.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2604.1.1**

    >

    > Date: **May 13, 2026**

    <div class="notification"> NOTE:<br>Some important API changes will be introduced. Please make sure to read the <a href="https://www.juniper.net/documentation/us/en/software/mist/api/http/guides/important-api-changes">announcements</a> </div>


    ---

    ## Additional Documentation

    * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html)

    * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html)

    * [Mist Product Updates](https://www.juniper.net/documentation/us/en/software/mist/product-updates/)


    ## Helpful Resources

    * [API Sandbox and Exercises](https://api-class.mist.com/)

    * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace)

    * [Python Script Examples](https://github.com/tmunzer/mist_library)

    * [API Demo Apps](https://apps.mist-lab.fr/)

    * [Juniper Blog](https://blogs.juniper.net/)


    ## Mist Web Browser Extension:

    * Google Chrome, Microsoft Edge and other Chromium-based browser: [Chrome Web Store](https://chromewebstore.google.com/detail/mist-extension/ejhpdcljeamillfhdihkkmoakanpbplh)

    * Firefox: [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/mist-extension/)


    ---'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist Sites Beacons API
  version: 2604.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Global 05
  url: https://api.gc4.mist.com
- description: Mist EMEA 01
  url: https://api.eu.mist.com
- description: Mist EMEA 02
  url: https://api.gc3.mist.com
- description: Mist EMEA 03
  url: https://api.ac6.mist.com
- description: Mist EMEA 04
  url: https://api.gc6.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
- description: Mist APAC 02
  url: https://api.gc5.mist.com
- description: Mist APAC 03
  url: https://api.gc7.mist.com
security:
- apiToken: []
- basicAuth: []
- basicAuth: []
  csrfToken: []
tags:
- name: Sites Beacons
paths:
  /api/v1/sites/{site_id}/beacons:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Get List of Site Beacons
      operationId: listSiteBeacons
      parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          $ref: '#/components/responses/BeaconsArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listSiteBeacons
      tags:
      - Sites Beacons
    post:
      description: Create Site Beacon
      operationId: createSiteBeacon
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  eddystone_instance: string
                  eddystone_namespace: string
                  eddystone_url: string
                  ibeacon_major: 1
                  ibeacon_minor: 1
                  ibeacon_uuid: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  mac: string
                  name: string
                  power: 0
                  type: eddystone-uid
                  x: 0
                  y: 0
            schema:
              $ref: '#/components/schemas/beacon'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Beacon'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: createSiteBeacon
      tags:
      - Sites Beacons
  /api/v1/sites/{site_id}/beacons/{beacon_id}:
    parameters:
    - $ref: '#/components/parameters/site_id'
    - $ref: '#/components/parameters/beacon_id'
    delete:
      description: Delete Site Beacon
      operationId: deleteSiteBeacon
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: deleteSiteBeacon
      tags:
      - Sites Beacons
    get:
      description: Get Site Beacon Details
      operationId: getSiteBeacon
      responses:
        '200':
          $ref: '#/components/responses/Beacon'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: getSiteBeacon
      tags:
      - Sites Beacons
    put:
      description: Update Site Beacon
      operationId: updateSiteBeacon
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  eddystone_instance: string
                  eddystone_namespace: string
                  eddystone_url: string
                  ibeacon_major: 1
                  ibeacon_minor: 1
                  ibeacon_uuid: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
                  mac: string
                  name: string
                  power: 0
                  type: eddystone-uid
                  x: 0
                  y: 0
            schema:
              $ref: '#/components/schemas/beacon'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Beacon'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: updateSiteBeacon
      tags:
      - Sites Beacons
components:
  schemas:
    beacon:
      description: Beacon
      properties:
        created_time:
          $ref: '#/components/schemas/created_time'
        eddystone_instance:
          description: Eddystone-UID instance (6 bytes) in hexstring format
          type: string
        eddystone_namespace:
          description: Eddystone-UID namespace (10 bytes) in hexstring format
          type: string
        eddystone_url:
          description: Eddystone-URL url
          type: string
        for_site:
          readOnly: true
          type: boolean
        ibeacon_major:
          $ref: '#/components/schemas/ibeacon_major'
        ibeacon_minor:
          $ref: '#/components/schemas/ibeacon_minor'
        ibeacon_uuid:
          $ref: '#/components/schemas/ibeacon_uuid'
        id:
          $ref: '#/components/schemas/id'
        mac:
          description: Optional, MAC of the beacon, currently used only to identify battery voltage
          type: string
        map_id:
          description: Map where the device belongs to
          format: uuid
          type: string
        modified_time:
          $ref: '#/components/schemas/modified_time'
        name:
          description: Name / label of the device
          type: string
        org_id:
          $ref: '#/components/schemas/org_id'
        power:
          default: -12
          description: In dBm
          maximum: 100
          minimum: -12
          type: integer
        site_id:
          $ref: '#/components/schemas/site_id'
        type:
          $ref: '#/components/schemas/beacon_type'
        x:
          description: X in pixel
          format: double
          type: number
        y:
          description: Y in pixel
          format: double
          type: number
      type: object
    response_http403:
      additionalProperties: false
      properties:
        detail:
          examples:
          - You do not have permission to perform this action.
          type: string
      type: object
    beacons:
      items:
        $ref: '#/components/schemas/beacon'
      type: array
    ibeacon_minor:
      description: Minor number for iBeacon
      examples:
      - 1234
      maximum: 65535
      minimum: 1
      type:
      - integer
      - 'null'
    org_id:
      examples:
      - a97c1b22-a4e9-411e-9bfd-d8695a0f9e61
      format: uuid
      readOnly: true
      type: string
    ibeacon_major:
      description: Major number for iBeacon
      examples:
      - 1234
      maximum: 65535
      minimum: 1
      type:
      - integer
      - 'null'
    response_http400:
      additionalProperties: false
      properties:
        detail:
          examples:
          - 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
          type: string
      type: object
    ibeacon_uuid:
      examples:
      - f3f17139-704a-f03a-2786-0400279e37c3
      format: uuid
      type:
      - string
      - 'null'
    modified_time:
      description: When the object has been modified for the last time, in epoch
      format: double
      readOnly: true
      type: number
    response_http404:
      additionalProperties: false
      properties:
        id:
          type: string
      type: object
    response_http401:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Authentication credentials were not provided.
          type: string
      type: object
    response_http429:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
          type: string
      type: object
    id:
      description: Unique ID of the object instance in the Mist Organization
      examples:
      - 53f10664-3ce8-4c27-b382-0ef66432349f
      format: uuid
      readOnly: true
      type: string
    site_id:
      examples:
      - 441a1214-6928-442a-8e92-e1d34b8ec6a6
      format: uuid
      readOnly: true
      type: string
    beacon_type:
      default: eddystone-uid
      description: 'enum: `eddystone-uid`, `eddystone-url`, `ibeacon`'
      enum:
      - eddystone-uid
      - eddystone-url
      - ibeacon
      type: string
    created_time:
      description: When the object has been created, in epoch
      format: double
      readOnly: true
      type: number
  parameters:
    site_id:
      in: path
      name: site_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    page:
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    beacon_id:
      in: path
      name: beacon_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    limit:
      in: query
      name: limit
      schema:
        default: 100
        minimum: 0
        type: integer
  responses:
    BeaconsArray:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/BeaconsArrayExample'
          schema:
            $ref: '#/components/schemas/beacons'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/BeaconsArrayExample'
          schema:
            $ref: '#/components/schemas/beacons'
      description: OK
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
      description: Unauthorized
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
      description: Bad Syntax
    Beacon:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/BeaconExample'
          schema:
            $ref: '#/components/schemas/beacon'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/BeaconExample'
          schema:
            $ref: '#/components/schemas/beacon'
      description: OK
    OK:
      description: OK
    HTTP404:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_http404'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_http404'
      description: Not found. The API endpoint doesn’t exist or resource doesn’ t exist
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
      description: Permission Denied
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
      description: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
  examples:
    HTTP400Example:
      value:
        detail: 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
    BeaconExample:
      value:
        created_time: 0
        eddystone_instance: string
        eddystone_namespace: string
        eddystone_url: string
        ibeacon_major: 1
        ibeacon_minor: 1
        ibeacon_uuid: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        mac: string
        map_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        modified_time: 0
        name: string
        org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        power: 0
        site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        type: eddystone-uid
        x: 0
        y: 0
    HTTP429Example:
      value:
        detail: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    HTTP403Example:
      value:
        detail: You do not have permission to perform this action.
    HTTP401Example:
      value:
        detail: Authentication credentials were not provided.
    BeaconsArrayExample:
      value:
      - created_time: 0
        eddystone_instance: string
        eddystone_namespace: string
        eddystone_url: string
        ibeacon_major: 1
        ibeacon_minor: 1
        ibeacon_uuid: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        mac: string
        map_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        modified_time: 0
        name: string
        org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        power: 0
        site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        type: eddystone-uid
        x: 0
        y: 0
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.
      scheme: basic
      type: http
    csrfToken:
      description: "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```"
      in: header
      name: X-CSRFToken
      type: apiKey
