openapi: 3.2.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2604.1.1**

    >

    > Date: **May 13, 2026**


    NOTE:

    Some important API changes will be introduced.'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist Sites Psks API
  version: 2604.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Global 05
  url: https://api.gc4.mist.com
- description: Mist EMEA 01
  url: https://api.eu.mist.com
- description: Mist EMEA 02
  url: https://api.gc3.mist.com
- description: Mist EMEA 03
  url: https://api.ac6.mist.com
- description: Mist EMEA 04
  url: https://api.gc6.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
- description: Mist APAC 02
  url: https://api.gc5.mist.com
- description: Mist APAC 03
  url: https://api.gc7.mist.com
security:
- apiToken: []
- basicAuth: []
- basicAuth: []
  csrfToken: []
tags:
- description: A multi PSK (Pre-Shared Key) is a feature that allows the use of multiple PSKs for securing network connections.
  name: Sites Psks
paths:
  /api/v1/sites/{site_id}/psks:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Get List of Site PSKs
      operationId: listSitePsks
      parameters:
      - in: query
        name: ssid
        schema:
          type: string
      - in: query
        name: role
        schema:
          type: string
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          $ref: '#/components/responses/PsksArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listSitePsks
      tags:
      - Sites Psks
    post:
      description: 'Create Site PSK


        When `usage`==`macs`, corresponding "macs" field will hold a list consisting of client mac addresses (["xx:xx:xx:xx:xx",...]) or mac patterns(["xx:xx:*","xx*",...]) or both (["xx:xx:xx:xx:xx:xx", "xx:*", ...]). This list is capped at 5000'
      operationId: createSitePsk
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  mac: string
                  name: string
                  passphrase: secretpsk
                  ssid: string
                  usage: multi
                  vlan_id: 1
            schema:
              $ref: '#/components/schemas/psk'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Psk'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: createSitePsk
      tags:
      - Sites Psks
    put:
      description: Update multiple PSKs
      operationId: updateSiteMultiplePsks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/psks'
      responses:
        '200':
          $ref: '#/components/responses/PsksArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: updateSiteMultiplePsks
      tags:
      - Sites Psks
  /api/v1/sites/{site_id}/psks/import:
    parameters:
    - $ref: '#/components/parameters/site_id'
    post:
      description: 'Import PSK from CSV file or JSON


        ## CSV File Format

        ```csv

        PSK Import CSV File Format:

        name,ssid,passphrase,usage,vlan_id,mac

        Common,warehouse,foryoureyesonly,single,35,a31425f31278

        Justin,reception,visible,multi,1002

        ```'
      operationId: importSitePsks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/psks'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/psks_import_file'
      responses:
        '200':
          $ref: '#/components/responses/PsksArray'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: importSitePsks
      tags:
      - Sites Psks
  /api/v1/sites/{site_id}/psks/{psk_id}:
    parameters:
    - $ref: '#/components/parameters/site_id'
    - $ref: '#/components/parameters/psk_id'
    delete:
      description: Delete Site PSK
      operationId: deleteSitePsk
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: deleteSitePsk
      tags:
      - Sites Psks
    get:
      description: Get Site PSK Details
      operationId: getSitePsk
      responses:
        '200':
          $ref: '#/components/responses/Psk'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: getSitePsk
      tags:
      - Sites Psks
    put:
      description: Update Site PSK
      operationId: updateSitePsk
      requestBody:
        content:
          application/json:
            examples:
              Example:
                value:
                  mac: string
                  name: string
                  passphrase: secretpsk
                  ssid: string
                  usage: multi
                  vlan_id: 1
            schema:
              $ref: '#/components/schemas/psk'
        description: Request Body
      responses:
        '200':
          $ref: '#/components/responses/Psk'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: updateSitePsk
      tags:
      - Sites Psks
components:
  schemas:
    psk_usage:
      default: multi
      description: 'enum: `macs`, `multi`, `single`'
      enum:
      - macs
      - multi
      - single
      type: string
    response_http400:
      additionalProperties: false
      properties:
        detail:
          examples:
          - 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
          type: string
      type: object
    psks_import_file:
      additionalProperties: false
      properties:
        file:
          contentMediaType: application/octet-stream
          type: string
      type: object
    created_time:
      description: When the object has been created, in epoch
      format: double
      readOnly: true
      type: number
    modified_time:
      description: When the object has been modified for the last time, in epoch
      format: double
      readOnly: true
      type: number
    site_id:
      examples:
      - 441a1214-6928-442a-8e92-e1d34b8ec6a6
      format: uuid
      readOnly: true
      type: string
    id:
      description: Unique ID of the object instance in the Mist Organization
      examples:
      - 53f10664-3ce8-4c27-b382-0ef66432349f
      format: uuid
      readOnly: true
      type: string
    response_http404:
      additionalProperties: false
      properties:
        id:
          type: string
      type: object
    psk:
      description: PSK
      properties:
        admin_sso_id:
          description: sso id for psk created from psk portal
          readOnly: true
          type: string
        created_time:
          $ref: '#/components/schemas/created_time'
        email:
          description: email to send psk expiring notifications to
          type: string
        expire_time:
          default: null
          description: Expire time for this PSK key (epoch time in seconds). Default `null` (as no expiration)
          examples:
          - 1614990263
          type:
          - integer
          - 'null'
        expiry_notification_time:
          description: Number of days before psk is expired. Used as to when to start sending reminder notification when the psk is about to expire
          type: integer
        id:
          $ref: '#/components/schemas/id'
        mac:
          description: If `usage`==`single`, the mac that this PSK ties to, empty if `auto-binding`
          type: string
        macs:
          $ref: '#/components/schemas/psk_macs'
        max_usage:
          default: 0
          description: For Org PSK Only. Max concurrent users for this PSK key. Default is 0 (unlimited)
          type: integer
        modified_time:
          $ref: '#/components/schemas/modified_time'
        name:
          type: string
        note:
          type: string
        notify_expiry:
          default: false
          description: If set to true, reminder notification will be sent when psk is about to expire
          type: boolean
        notify_on_create_or_edit:
          description: If set to true, notification will be sent when psk is created or edited
          type: boolean
        old_passphrase:
          description: previous passphrase of the PSK if it has been rotated
          type: string
        org_id:
          $ref: '#/components/schemas/org_id'
        passphrase:
          description: passphrase of the PSK (8-63 character or 64 in hex)
          maxLength: 64
          minLength: 8
          type: string
        role:
          maxLength: 32
          minLength: 0
          type: string
        site_id:
          $ref: '#/components/schemas/site_id'
        ssid:
          description: SSID this PSK should be applicable to
          type: string
        usage:
          $ref: '#/components/schemas/psk_usage'
        vlan_id:
          $ref: '#/components/schemas/psk_vlan_id'
        vlan_name:
          description: VLAN name to be assigned. Optional, `vlan_id` takes precedence if both are provided
          type: string
      required:
      - name
      - passphrase
      - ssid
      type: object
    response_http401:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Authentication credentials were not provided.
          type: string
      type: object
    response_http429:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
          type: string
      type: object
    org_id:
      examples:
      - a97c1b22-a4e9-411e-9bfd-d8695a0f9e61
      format: uuid
      readOnly: true
      type: string
    psk_list:
      items:
        $ref: '#/components/schemas/psk'
      type: array
    response_http403:
      additionalProperties: false
      properties:
        detail:
          examples:
          - You do not have permission to perform this action.
          type: string
      type: object
    psks:
      items:
        $ref: '#/components/schemas/psk'
      type: array
      uniqueItems: true
    psk_macs:
      description: If `usage`==`macs`, this list contains N number of client mac addresses or mac patterns(1122*) or both. This list is capped at 5000
      examples:
      - - 112233abcedf
        - aabbcc*
      items:
        type: string
      type: array
    psk_vlan_id:
      description: VLAN for this PSK key
      oneOf:
      - type: string
      - maximum: 4094
        minimum: 1
        type: integer
  parameters:
    site_id:
      in: path
      name: site_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    page:
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    psk_id:
      description: PSK ID
      in: path
      name: psk_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    name:
      in: query
      name: name
      schema:
        type: string
    limit:
      in: query
      name: limit
      schema:
        default: 100
        minimum: 0
        type: integer
  responses:
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
      description: Bad Syntax
    HTTP404:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_http404'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_http404'
      description: Not found. The API endpoint doesn’t exist or resource doesn’ t exist
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
      description: Unauthorized
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
      description: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
      description: Permission Denied
    Psk:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/psk'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/psk'
      description: OK
    OK:
      description: OK
    PsksArray:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/PsksArrayExample'
          schema:
            $ref: '#/components/schemas/psk_list'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/PsksArrayExample'
          schema:
            $ref: '#/components/schemas/psk_list'
      description: OK
  examples:
    HTTP400Example:
      value:
        detail: 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
    HTTP401Example:
      value:
        detail: Authentication credentials were not provided.
    HTTP429Example:
      value:
        detail: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    PsksArrayExample:
      value:
      - created_time: 0
        id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        mac: string
        modified_time: 0
        name: string
        org_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        passphrase: secretpsk
        site_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        ssid: string
        usage: multi
        vlan_id: 1
    HTTP403Example:
      value:
        detail: You do not have permission to perform this action.
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.
      scheme: basic
      type: http
    csrfToken:
      description: "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```"
      in: header
      name: X-CSRFToken
      type: apiKey
