openapi: 3.1.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2604.1.1**

    >

    > Date: **May 13, 2026**

    <div class="notification"> NOTE:<br>Some important API changes will be introduced. Please make sure to read the <a href="https://www.juniper.net/documentation/us/en/software/mist/api/http/guides/important-api-changes">announcements</a> </div>


    ---

    ## Additional Documentation

    * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html)

    * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html)

    * [Mist Product Updates](https://www.juniper.net/documentation/us/en/software/mist/product-updates/)


    ## Helpful Resources

    * [API Sandbox and Exercises](https://api-class.mist.com/)

    * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace)

    * [Python Script Examples](https://github.com/tmunzer/mist_library)

    * [API Demo Apps](https://apps.mist-lab.fr/)

    * [Juniper Blog](https://blogs.juniper.net/)


    ## Mist Web Browser Extension:

    * Google Chrome, Microsoft Edge and other Chromium-based browser: [Chrome Web Store](https://chromewebstore.google.com/detail/mist-extension/ejhpdcljeamillfhdihkkmoakanpbplh)

    * Firefox: [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/mist-extension/)


    ---'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist Admins Orgs SLEs API
  version: 2604.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Global 05
  url: https://api.gc4.mist.com
- description: Mist EMEA 01
  url: https://api.eu.mist.com
- description: Mist EMEA 02
  url: https://api.gc3.mist.com
- description: Mist EMEA 03
  url: https://api.ac6.mist.com
- description: Mist EMEA 04
  url: https://api.gc6.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
- description: Mist APAC 02
  url: https://api.gc5.mist.com
- description: Mist APAC 03
  url: https://api.gc7.mist.com
security:
- apiToken: []
- basicAuth: []
- basicAuth: []
  csrfToken: []
tags:
- description: 'Org SLEs, or Service-Level Expectations, are metrics used to monitor and report on the user experience of a Wireless, Wired or Wan network.


    They are generated through data science and machine learning algorithms and provide insights into various aspects of the network, such as coverage, capacity, connectivity, and performance.


    Mist SLEs help identify when users do not have sufficient network quality, when they face issues with connecting or roaming between access points, and when there are problems on the wired network.'
  name: Orgs SLEs
paths:
  /api/v1/orgs/{org_id}/insights/sites-sle:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get Org Sites SLE
      operationId: getOrgSitesSle
      parameters:
      - in: query
        name: sle
        schema:
          $ref: '#/components/schemas/org_site_sle_type'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/interval'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          $ref: '#/components/responses/OrgSiteSle'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: getOrgSitesSle
      tags:
      - Orgs SLEs
  /api/v1/orgs/{org_id}/insights/{metric}:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/metric'
    get:
      description: Get Org SLEs (all/worst sites, Mx Edges, ...)
      operationId: getOrgSle
      parameters:
      - description: See [List Insight Metrics](/#operations/listInsightMetrics) for more details
        in: query
        name: sle
        schema:
          type: string
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/interval'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      responses:
        '200':
          $ref: '#/components/responses/InsightMetricOrg'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: getOrgSle
      tags:
      - Orgs SLEs
components:
  responses:
    OrgSiteSle:
      content:
        application/json:
          examples:
            WAN SLE:
              $ref: '#/components/examples/OrgSiteSleWANSLE'
            Wi-Fi SLE:
              $ref: '#/components/examples/OrgSiteSleWiFiSLE'
            Wired SLE:
              $ref: '#/components/examples/OrgSiteSleWiredSLE'
          schema:
            $ref: '#/components/schemas/response_org_site_sle'
        application/vnd.api+json:
          examples:
            WAN SLE:
              $ref: '#/components/examples/OrgSiteSleWANSLE'
            Wi-Fi SLE:
              $ref: '#/components/examples/OrgSiteSleWiFiSLE'
            Wired SLE:
              $ref: '#/components/examples/OrgSiteSleWiredSLE'
          schema:
            $ref: '#/components/schemas/response_org_site_sle'
      description: Example response
    HTTP404:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_http404'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_http404'
      description: Not found. The API endpoint doesn’t exist or resource doesn’ t exist
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
      description: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    InsightMetricOrg:
      content:
        application/json:
          examples:
            Worst Sites By Sle:
              $ref: '#/components/examples/InsightMetricOrgWorstSitesBySle'
          schema:
            $ref: '#/components/schemas/insight_metrics'
        application/vnd.api+json:
          examples:
            Worst Sites By Sle:
              $ref: '#/components/examples/InsightMetricOrgWorstSitesBySle'
          schema:
            $ref: '#/components/schemas/insight_metrics'
      description: OK
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
      description: Permission Denied
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
      description: Bad Syntax
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
      description: Unauthorized
  parameters:
    interval:
      description: Aggregation works by giving a time range plus interval (e.g. 1d, 1h, 10m) where aggregation function would be applied to.
      in: query
      name: interval
      schema:
        examples:
        - 10m
        type: string
    org_id:
      in: path
      name: org_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    start:
      description: Start time (epoch timestamp in seconds, or relative string like "-1d", "-1w")
      in: query
      name: start
      schema:
        type: string
    duration:
      description: Duration like 7d, 2w
      in: query
      name: duration
      schema:
        default: 1d
        examples:
        - 10m
        type: string
    page:
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    end:
      description: End time (epoch timestamp in seconds, or relative string like "-1d", "-2h", "now")
      in: query
      name: end
      schema:
        type: string
    metric:
      description: See [List Insight Metrics](/#operations/listInsightMetrics) for available metrics
      in: path
      name: metric
      required: true
      schema:
        type: string
    limit:
      in: query
      name: limit
      schema:
        default: 100
        minimum: 0
        type: integer
  schemas:
    org_site_sle_wan_results:
      items:
        $ref: '#/components/schemas/org_site_sle_wan_result'
      type: array
      uniqueItems: true
    response_http403:
      additionalProperties: false
      properties:
        detail:
          examples:
          - You do not have permission to perform this action.
          type: string
      type: object
    org_site_sle_wan_result:
      additionalProperties: false
      properties:
        application_health:
          type: number
        gateway-health:
          type: number
        num_clients:
          type: number
        num_gateways:
          type: number
        site_id:
          $ref: '#/components/schemas/site_id'
        wan-link-health:
          type: number
      required:
      - site_id
      - gateway-health
      type: object
    org_site_wan_wifi:
      additionalProperties: false
      properties:
        end:
          type: number
        interval:
          type: integer
        limit:
          type: integer
        page:
          type: integer
        results:
          $ref: '#/components/schemas/org_site_sle_wan_results'
        start:
          type: number
        total:
          type: integer
      required:
      - start
      - end
      - interval
      - limit
      - page
      - total
      - results
      type: object
    org_site_sle_wifi_results:
      items:
        $ref: '#/components/schemas/org_site_sle_wifi_result'
      type: array
      uniqueItems: true
    insight_metrics_results:
      description: Results depends on the `metric` - some return numbers (e.g. bytes, ap-count), others return objects
      items:
        $ref: '#/components/schemas/insight_metrics_results_item'
      type: array
      uniqueItems: true
    response_org_site_sle:
      oneOf:
      - $ref: '#/components/schemas/org_site_sle_wifi'
      - $ref: '#/components/schemas/org_site_wired_wifi'
      - $ref: '#/components/schemas/org_site_wan_wifi'
    org_site_sle_wifi_result:
      additionalProperties: false
      properties:
        ap-availability:
          type: number
        ap-health:
          type: number
        capacity:
          type: number
        coverage:
          type: number
        num_aps:
          type: number
        num_clients:
          type: number
        roaming:
          type: number
        site_id:
          $ref: '#/components/schemas/site_id'
        successful-connect:
          type: number
        throughput:
          type: number
        time-to-connect:
          type: number
      required:
      - site_id
      - ap-availability
      type: object
    site_id:
      examples:
      - 441a1214-6928-442a-8e92-e1d34b8ec6a6
      format: uuid
      readOnly: true
      type: string
    response_http404:
      additionalProperties: false
      properties:
        id:
          type: string
      type: object
    org_site_sle_wired_result:
      additionalProperties: false
      properties:
        num_clients:
          type: number
        num_switches:
          type: number
        site_id:
          $ref: '#/components/schemas/site_id'
        switch-bandwidth:
          type: number
        switch-health:
          type: number
        switch-throughput:
          type: number
      required:
      - site_id
      - switch-health
      type: object
    insight_metrics_results_item:
      anyOf:
      - type: number
      - additionalProperties: true
        type: object
    response_http400:
      additionalProperties: false
      properties:
        detail:
          examples:
          - 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
          type: string
      type: object
    response_http429:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
          type: string
      type: object
    org_site_sle_wired_results:
      items:
        $ref: '#/components/schemas/org_site_sle_wired_result'
      type: array
      uniqueItems: true
    org_site_sle_wifi:
      additionalProperties: false
      properties:
        end:
          type: number
        interval:
          type: integer
        limit:
          type: integer
        page:
          type: integer
        results:
          $ref: '#/components/schemas/org_site_sle_wifi_results'
        start:
          type: number
        total:
          type: integer
      required:
      - start
      - end
      - interval
      - limit
      - page
      - total
      - results
      type: object
    org_site_wired_wifi:
      additionalProperties: false
      properties:
        end:
          type: number
        interval:
          type: integer
        limit:
          type: integer
        page:
          type: integer
        results:
          $ref: '#/components/schemas/org_site_sle_wired_results'
        start:
          type: number
        total:
          type: integer
      required:
      - start
      - end
      - interval
      - limit
      - page
      - total
      - results
      type: object
    org_site_sle_type:
      description: 'enum: `wan`, `wifi`, `wired`'
      enum:
      - wan
      - wifi
      - wired
      type: string
    response_http401:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Authentication credentials were not provided.
          type: string
      type: object
    insight_metrics:
      additionalProperties: false
      properties:
        end:
          type: integer
        interval:
          type: integer
        limit:
          type: integer
        results:
          $ref: '#/components/schemas/insight_metrics_results'
        start:
          type: integer
      required:
      - end
      - interval
      - start
      type: object
  examples:
    InsightMetricOrgWorstSitesBySle:
      value:
        end: 1643706000
        interval: 3600
        limit: 100
        results:
        - ap-availability: 0.9919400860511628
          ap-health: 0.967607512909879
          capacity: 0.7484652273070254
          coverage: 0.91217567374857
          num_aps: 13
          num_clients: 12
          roaming: 0.991735537682683
          roaming-exp: 0.991735537682683
          site_id: ab0aca7a-d45c-469b-b3bb-4fe240642d0b
          successful-connect: 0.46052632135780236
          throughput: 0.6775702123846302
          time-to-connect: 0.9349112447196916
        - ap-availability: 0.9990384613092129
          ap-health: 0.48201754375507955
          capacity: 0.9702673450306101
          coverage: 0.8335392334930375
          num_aps: 1
          num_clients: 6
          roaming: 1
          roaming-exp: 1
          site_id: 49ff76e0-a283-4e7d-b38d-041f1e9aff3c
          successful-connect: 1
          throughput: 0
          time-to-connect: 1
        - ap-availability: 1
          ap-health: 0.982456140612301
          capacity: 1
          coverage: 0.9276041182442488
          num_aps: 2
          num_clients: 3
          roaming: 1
          roaming-exp: 1
          site_id: 9b9b48f1-15a4-459e-86cc-9cbec9005983
          successful-connect: 1
          throughput: 1
          time-to-connect: 0.8125
        - ap-availability: 0.9981132070973234
          ap-health: 0.9991228068084047
          capacity: 1
          coverage: 1
          num_aps: 1
          num_clients: 0
          roaming: 1
          roaming-exp: 1
          site_id: eb0e1671-7a6b-472b-94c3-c187dafe5274
          successful-connect: 1
          throughput: 0
          time-to-connect: 0.5
        start: 1643670000
    OrgSiteSleWiFiSLE:
      value:
        end: 1651323600
        interval: 3600
        limit: 1
        page: 2
        results:
        - ap-availability: 1
          ap-health: 0.6735632316819553
          capacity: 0.9802900770150502
          coverage: 0.812181632387686
          num_aps: 3
          num_clients: 24
          roaming: 1
          site_id: f5fcbee5-1234-5678-9101-1619ede87879
          successful-connect: 0.9535864983932881
          throughput: 1
          time-to-connect: 0.9791666666666666
        start: 1651269600
        total: 4
    OrgSiteSleWANSLE:
      value:
        end: 1651323600
        interval: 3600
        limit: 1
        page: 2
        results:
        - application_health: 0.8250000047942866
          gateway-health: 1
          num_clients: 65
          num_gateways: 1
          site_id: f5fcbee5-1234-5678-9101-1619ede87879
          wan-link-health: 0.9988471089272484
        start: 1651269600
        total: 4
    HTTP400Example:
      value:
        detail: 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
    HTTP403Example:
      value:
        detail: You do not have permission to perform this action.
    HTTP429Example:
      value:
        detail: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    HTTP401Example:
      value:
        detail: Authentication credentials were not provided.
    OrgSiteSleWiredSLE:
      value:
        end: 1651323600
        interval: 3600
        limit: 1
        page: 2
        results:
        - num_clients: 6
          num_switches: 1
          site_id: f5fcbee5-1234-5678-9101-1619ede87879
          switch-bandwidth: 0.9669529756744796
          switch-health: 1
          switch-throughput: 1
        start: 1651269600
        total: 4
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.
      scheme: basic
      type: http
    csrfToken:
      description: "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```"
      in: header
      name: X-CSRFToken
      type: apiKey
