openapi: 3.2.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2604.1.1**

    >

    > Date: **May 13, 2026**

    <div class="notification"> NOTE:<br>Some important API changes will be introduced. Please make sure to read the <a href="https://www.juniper.net/documentation/us/en/software/mist/api/http/guides/important-api-changes">announcements</a> </div>


    ---

    ## Additional Documentation

    * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html)

    * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html)

    * [Mist Product Updates](https://www.juniper.net/documentation/us/en/software/mist/product-updates/)


    ## Helpful Resources

    * [API Sandbox and Exercises](https://api-class.mist.com/)

    * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace)

    * [Python Script Examples](https://github.com/tmunzer/mist_library)

    * [API Demo Apps](https://apps.mist-lab.fr/)

    * [Juniper Blog](https://blogs.juniper.net/)


    ## Mist Web Browser Extension:

    * Google Chrome, Microsoft Edge and other Chromium-based browser: [Chrome Web Store](https://chromewebstore.google.com/detail/mist-extension/ejhpdcljeamillfhdihkkmoakanpbplh)

    * Firefox: [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/mist-extension/)


    ---'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist Orgs JSI API
  version: 2604.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Global 05
  url: https://api.gc4.mist.com
- description: Mist EMEA 01
  url: https://api.eu.mist.com
- description: Mist EMEA 02
  url: https://api.gc3.mist.com
- description: Mist EMEA 03
  url: https://api.ac6.mist.com
- description: Mist EMEA 04
  url: https://api.gc6.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
- description: Mist APAC 02
  url: https://api.gc5.mist.com
- description: Mist APAC 03
  url: https://api.gc7.mist.com
security:
- apiToken: []
- basicAuth: []
- basicAuth: []
  csrfToken: []
tags:
- description: "Juniper Support Insight is a free service provided to all Mist customers.\nYou can adopt your devices via a few lines CLI commands. Allowing you to \n* get some basic information about the adopted devices \n* web shell into device (write privilege required) \\n* upgrade (write privilege required)"
  name: Orgs JSI
paths:
  /api/v1/orgs/{org_id}/jsi/devices:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get List of Org devices that connected to JSI
      operationId: listOrgJsiDevices
      parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      - description: Device model
        in: query
        name: model
        schema:
          examples:
          - AP43
          type: string
      - description: Device serial
        in: query
        name: serial
        schema:
          examples:
          - FXLH2015150025
          type: string
      - description: Device MAC Address
        in: query
        name: mac
        schema:
          examples:
          - 5c5b350e0001
          type: string
      responses:
        '200':
          $ref: '#/components/responses/JsiDevices'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listOrgJsiDevices
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/devices/outbound_ssh_cmd:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Adopt JSI devices
      operationId: adoptOrgJsiDevice
      responses:
        '200':
          $ref: '#/components/responses/JunosRegisterCmd'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: adoptOrgJsiDevice
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/devices/{device_mac}/shell:
    parameters:
    - $ref: '#/components/parameters/org_id'
    - $ref: '#/components/parameters/device_mac'
    post:
      description: Create Shell Session
      operationId: createOrgJsiDeviceShellSession
      responses:
        '200':
          $ref: '#/components/responses/WebsocketSessionWithUrl'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: createOrgJsiDeviceShellSession
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/inventory:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: "This gets all devices purchased from the accounts associated with the Org \n  * Fetch Install base devices for all linked accounts and associated account of the linked accounts. \n  * The primary and the associated account ids will be queries from SFDC by passing the linked account \n  * Returns only the device centric details of the Install base device. No customer specific information will be returned."
      operationId: listOrgJsiPastPurchases
      parameters:
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      - in: query
        name: model
        schema:
          examples:
          - AP43
          type: string
      - in: query
        name: serial
        schema:
          examples:
          - FXLH2015150025
          type: string
      responses:
        '200':
          $ref: '#/components/responses/JsiInventory'
        '400':
          $ref: '#/components/responses/JsiInventoryError'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: listOrgJsiPastPurchases
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/inventory/count:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Count devices purchased from the accounts associated with the Org
      operationId: countOrgJsiAssetsAndContracts
      parameters:
      - description: Distinct attributes to count
        in: query
        name: distinct
        schema:
          $ref: '#/components/schemas/jsi_inventory_count_distinct'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          $ref: '#/components/responses/Count'
        '400':
          $ref: '#/components/responses/JsiInventoryError'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countOrgJsiAssetsAndContracts
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/inventory/search:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: "This gets all devices purchased from the accounts associated with the Org \n  * Fetch Install base devices for all linked accounts and associated account of the linked accounts. \n  * The primary and the associated account ids will be queries from SFDC by passing the linked account \n  * Returns only the device centric details of the Install base device. No customer specific information will be returned."
      operationId: searchOrgJsiAssetsAndContracts
      parameters:
      - description: Device claim status, `true` for claimed devices, `false` for all devices
        in: query
        name: claimed
        schema:
          examples:
          - true
          type: boolean
      - description: Device model
        in: query
        name: model
        schema:
          examples:
          - AP43
          type: string
      - description: Device serial
        in: query
        name: serial
        schema:
          examples:
          - FXLH2015150025
          type: string
      - description: SKU name of the device
        in: query
        name: sku
        schema:
          examples:
          - EX2300
          type: string
      - description: Device status
        in: query
        name: status
        schema:
          $ref: '#/components/schemas/device_status'
      - description: Device warranty type
        in: query
        name: warranty_type
        schema:
          $ref: '#/components/schemas/jsi_warranty_type'
      - description: Filter devices with End Of Life date after this date
        in: query
        name: eol_after
        schema:
          examples:
          - '2024-01-01'
          type: string
      - description: Filter devices with End Of Life date before this date
        in: query
        name: eol_before
        schema:
          examples:
          - '2025-12-31'
          type: string
      - description: Filter devices with End Of Support date after this date
        in: query
        name: eos_after
        schema:
          examples:
          - '2024-01-01'
          type: string
      - description: Filter devices with End Of Support date before this date
        in: query
        name: eos_before
        schema:
          examples:
          - '2025-12-31'
          type: string
      - description: Filter devices with OS Version End Of Support date after this date
        in: query
        name: version_eos_after
        schema:
          examples:
          - '2024-01-01'
          type: string
      - description: Filter devices with OS Version End Of Support date before this date
        in: query
        name: version_eos_before
        schema:
          examples:
          - '2025-12-31'
          type: string
      - description: Indicates if the device is covered under active support contract
        in: query
        name: has_support
        schema:
          examples:
          - true
          type: boolean
      - description: To get the onboarded devices that are affected by the SIRT ID
        in: query
        name: sirt_id
        schema:
          examples:
          - JSA12345
          type: string
      - description: To get the onboarded devices that are affected by the PBN ID
        in: query
        name: pbn_id
        schema:
          examples:
          - PBN67890
          type: string
      - description: Wildcards for `serial`, `model`, `account_id`
        in: query
        name: text
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search_after'
      responses:
        '200':
          $ref: '#/components/responses/JsiInventorySearch'
        '400':
          $ref: '#/components/responses/JsiInventoryError'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchOrgJsiAssetsAndContracts
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/pbn/count:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get count of PBN advisories grouped by specified field
      operationId: countOrgJsiPbn
      parameters:
      - description: 'Field to group by enum: `versions`, `models`, `customer_risk`, `bug_type`'
        in: query
        name: distinct
        required: true
        schema:
          $ref: '#/components/schemas/count_pbn_distinct'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      responses:
        '200':
          $ref: '#/components/responses/JsiPbnCount'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countOrgJsiPbn
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/pbn/search:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Text search for PBN (Problem Bug Notification) advisories. Search can be done on versions, models, customer_risk, id, and bug_type fields.
      operationId: searchOrgJsiPbn
      parameters:
      - description: OS versions to search for
        in: query
        name: versions
        schema:
          examples:
          - 20.4R3
          type: string
      - description: Device models to search for
        in: query
        name: models
        schema:
          type: string
      - description: Customer risk level to filter by
        in: query
        name: customer_risk
        schema:
          type: string
      - description: PBN ID to search for
        in: query
        name: id
        schema:
          examples:
          - '1403338'
          type: string
      - description: Bug type to filter by
        in: query
        name: bug_type
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/search_after'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      responses:
        '200':
          $ref: '#/components/responses/JsiPbnSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchOrgJsiPbn
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/sirt/count:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Get count of SIRT advisories grouped by specified field
      operationId: countOrgJsiSirt
      parameters:
      - description: 'Field to group by. enum: `jsa_updated_date`, `models`, `severity`, `versions`'
        in: query
        name: distinct
        required: true
        schema:
          $ref: '#/components/schemas/count_sirt_distinct'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      responses:
        '200':
          $ref: '#/components/responses/JsiSirtCount'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countOrgJsiSirt
      tags:
      - Orgs JSI
  /api/v1/orgs/{org_id}/jsi/sirt/search:
    parameters:
    - $ref: '#/components/parameters/org_id'
    get:
      description: Search and get all the SIRT for the onboarded devices. Search can be done on severity, id, updated_after, updated_before, published_after, published_before, models, versions, and text fields.
      operationId: searchOrgJsiSirt
      parameters:
      - description: Severity of the SIRT (Critical, High, Medium, Low)
        in: query
        name: severity
        schema:
          type: string
      - description: JSA number
        in: query
        name: id
        schema:
          examples:
          - JSA100053
          type: string
      - description: JSA Updated date to be filtered after this date
        in: query
        name: updated_after
        schema:
          type: string
      - description: JSA Updated date to be filtered before this date
        in: query
        name: updated_before
        schema:
          type: string
      - description: JSA Published date to be filtered after this date
        in: query
        name: published_after
        schema:
          type: string
      - description: JSA Published date to be filtered before this date
        in: query
        name: published_before
        schema:
          type: string
      - description: Models affected by the SIRT
        in: query
        name: models
        schema:
          type: string
      - description: Software version affected by the SIRT
        in: query
        name: versions
        schema:
          examples:
          - 20.4R3
          type: string
      - description: Wildcards search on os_version_affected, affected_models, severity, jsa_id
        in: query
        name: text
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search_after'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      responses:
        '200':
          $ref: '#/components/responses/JsiSirtSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchOrgJsiSirt
      tags:
      - Orgs JSI
components:
  examples:
    JunosRegisterCmdExample:
      value:
        cmd: 'set system services ssh...

          ...

          set system services outbound-ssh client mist ...'
    JsiDevicesExample:
      value:
      - ext_ip: 73.92.124.103
        last_seen: 1654636867
        mac: c15353123096
        model: EX2300-C-12P
        serial: DGCOO0015
    JsiInventoryErrorNoJuniperAccountLinked:
      value:
        detail: no juniper account linked
    HTTP400Example:
      value:
        detail: 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
    HTTP429Example:
      value:
        detail: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    JsiInventoryExample:
      value:
      - device_name: name1
        eol_time: 1561507200
        eos_time: 1672012800
        master: true
        model: EX2300-24MP
        org_id: 6e843b41-f953-4af9-80e5-e1a70f65754a
        serial: XN3123300095
        sku: EX2300
        status: connected
        suggested_version: Latest 21.4R3-Sx
        type: switch
        version: 23.4R2-S4.11
        version_eos_time: 1672012800
        version_time: 1561507200
        warranty: Enhanced Hardware Warranty
        warranty_time: 1672012800
        warranty_type: Enhanced Hardware Warranty
    HTTP403Example:
      value:
        detail: You do not have permission to perform this action.
    HTTP401Example:
      value:
        detail: Authentication credentials were not provided.
    JsiInventorySearchExample:
      value:
        end: 1748023308
        limit: 1000
        results:
        - claimed: true
          device_name: name1
          eol_time: 1561507200
          eos_time: 1672012800
          has_support: true
          master: true
          model: EX2300-24MP
          org_id: 6e843b41-f953-4af9-80e5-e1a70f65754a
          serial: XN3123300095
          sku: EX2300
          status: connected
          suggested_version: Latest 21.4R3-Sx
          type: switch
          version: 23.4R2-S4.11
          version_eos_time: 1672012800
          version_time: 1561507200
          warranty: Enhanced Hardware Warranty
          warranty_time: 1672012800
          warranty_type: Enhanced Hardware Warranty
        start: 1748019708
        total: 1
    CountExample:
      value:
        distinct: string
        end: 0
        limit: 0
        results:
        - count: 0
          property: string
        start: 0
        total: 0
  schemas:
    response_http403:
      additionalProperties: false
      properties:
        detail:
          examples:
          - You do not have permission to perform this action.
          type: string
      type: object
    js_inventory_search:
      additionalProperties: false
      properties:
        end:
          description: Offset to end at
          type: integer
        limit:
          description: Number of results to return
          type: integer
        next:
          type: string
        results:
          $ref: '#/components/schemas/js_inventory'
        start:
          description: Offset to start from
          type: integer
        total:
          description: Total number of results
          type: integer
      type: object
    org_id:
      examples:
      - a97c1b22-a4e9-411e-9bfd-d8695a0f9e61
      format: uuid
      readOnly: true
      type: string
    jse_device:
      additionalProperties: false
      properties:
        ext_ip:
          description: When available
          type: string
        last_seen:
          $ref: '#/components/schemas/last_seen'
        mac:
          type: string
        model:
          type: string
        serial:
          type: string
      type: object
    response_http400:
      additionalProperties: false
      properties:
        detail:
          examples:
          - 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
          type: string
      type: object
    jsi_sirt_item:
      additionalProperties: false
      description: SIRT advisory item
      properties:
        cvss_score:
          description: CVSS score
          type: number
        id:
          description: ID of the SIRT
          examples:
          - JSA100053
          type: string
        models:
          description: OS models affected
          items:
            type: string
          type: array
        problem:
          description: Problem description
          type: string
        published_date:
          description: Release date of the SIRT issue
          type: integer
        release_notes:
          description: Release notes if any
          type: string
        severity:
          description: Severity of the issue
          type: string
        solution:
          description: Solution for the security issue
          type: string
        title:
          description: Title of the SIRT
          type: string
        updated_date:
          description: JSA updated timestamp
          type: integer
        versions:
          description: OS versions affected
          items:
            type: string
          type: array
        workaround:
          description: Workaround provided
          type: string
      type: object
    response_device_config_cmd:
      additionalProperties: false
      properties:
        cmd:
          type: string
      required:
      - cmd
      type: object
    response_count:
      additionalProperties: false
      properties:
        distinct:
          type: string
        end:
          type: integer
        limit:
          type: integer
        results:
          $ref: '#/components/schemas/count_results'
        start:
          type: integer
        total:
          type: integer
      required:
      - distinct
      - end
      - limit
      - results
      - start
      - total
      type: object
    js_inventory:
      items:
        $ref: '#/components/schemas/js_inventory_item'
      type: array
    device_status:
      default: all
      description: 'enum: `all`, `connected`, `disconnected`'
      enum:
      - all
      - connected
      - disconnected
      type: string
    jsi_pbn_search:
      additionalProperties: false
      description: PBN search response
      properties:
        end:
          description: End timestamp
          type: integer
        limit:
          description: Number of results to return
          type: integer
        next:
          description: Next page URL
          type: string
        results:
          description: List of PBN advisories
          items:
            $ref: '#/components/schemas/jsi_pbn_item'
          type: array
        start:
          description: Start timestamp
          type: integer
        total:
          description: Total number of results
          type: integer
      type: object
    jsi_sirt_search:
      additionalProperties: false
      description: SIRT search response
      properties:
        end:
          description: End timestamp
          type: integer
        limit:
          description: Number of results to return
          type: integer
        next:
          description: Next page URL
          type: string
        results:
          description: List of SIRT advisories
          items:
            $ref: '#/components/schemas/jsi_sirt_item'
          type: array
        start:
          description: Start timestamp
          type: integer
        total:
          description: Total number of results
          type: integer
      type: object
    count_sirt_distinct:
      enum:
      - versions
      - models
      - severity
      - jsa_updated_date
      examples:
      - versions
      type: string
    jse_devices:
      items:
        $ref: '#/components/schemas/jse_device'
      type: array
    jsi_inventory_count_distinct:
      description: 'enum: `account_id`, `claimed`, `eol_time`, `eos_time`, `has_support`, `version_time`, `model`, `sku`, `status`, `type`, `version`, `warranty_type'
      enum:
      - account_id
      - claimed
      - has_support
      - eol_time
      - eos_time
      - version_time
      - model
      - sku
      - status
      - type
      - version
      - warranty_type
      type: string
    device_type:
      description: 'enum: `ap`, `gateway`, `switch`'
      enum:
      - ap
      - gateway
      - switch
      type: string
    count_results:
      items:
        $ref: '#/components/schemas/count_result'
      type: array
      uniqueItems: true
    last_seen:
      description: Last seen timestamp
      examples:
      - 1470417522
      format: double
      readOnly: true
      type:
      - number
      - 'null'
    count_result:
      additionalProperties:
        type: string
      properties:
        count:
          type: integer
      required:
      - count
      type: object
    websocket_session_with_url:
      additionalProperties: false
      properties:
        session:
          examples:
          - 19e73828-937f-05e6-f709-e29efdb0a82b
          type: string
        url:
          examples:
          - wss://api-ws.mist.com/ssh?jwt=xxxx
          type: string
      required:
      - session
      - url
      type: object
    count_pbn_distinct:
      enum:
      - versions
      - models
      - customer_risk
      - bug_type
      examples:
      - versions
      type: string
    jsi_pbn_item:
      additionalProperties: false
      description: PBN (Problem Bug Notification) advisory item
      properties:
        bug_type:
          description: Type of the bug (Day-1, Regression)
          type: string
        customer_risk:
          description: Risk level
          type: string
        fixed_in:
          description: Release in which the issue was fixed
          type: string
        id:
          description: ID of the PBN
          examples:
          - '1403338'
          type: string
        introduced_in:
          description: Release introduced in
          type: string
        models:
          description: OS models affected
          items:
            type: string
          type: array
        product_family:
          description: Product family affected
          type: string
        release_notes:
          description: Release notes for this PBN
          type: string
        restoration:
          description: Restoration steps
          type: string
        title:
          description: Title of the issue
          type: string
        updated_date:
          description: PBN updated timestamp
          type: integer
        versions:
          description: OS versions affected
          items:
            type: string
          type: array
        workaround:
          description: Workaround for this issue
          type: string
        workaround_provided:
          description: Any workaround available
          type: string
      type: object
    response_http404:
      additionalProperties: false
      properties:
        id:
          type: string
      type: object
    response_http429:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
          type: string
      type: object
    response_http401:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Authentication credentials were not provided.
          type: string
      type: object
    response_detail_string:
      additionalProperties: false
      properties:
        detail:
          type: string
      type: object
    js_inventory_item:
      additionalProperties: false
      properties:
        claimed:
          description: Indicates if the device is claimed by any org
          type: boolean
        device_name:
          description: Name of the device
          type: string
        eol_psn:
          description: EOL PSN
          examples:
          - TSB18097
          type: string
        eol_time:
          description: End of life time
          type: integer
        eos_time:
          description: End of support time
          type: integer
        has_support:
          description: Indicates if the device is covered under active support contract
          type: boolean
        master:
          description: Indicates whether it is Master
          type: boolean
        model:
          description: Model of the install base inventory
          type: string
        org_id:
          $ref: '#/components/schemas/org_id'
        serial:
          description: Serial Number of the inventory
          type: string
        sku:
          description: Serviceable device stock
          type: string
        status:
          description: Status of the connected device
          type: string
        suggested_version:
          description: Suggested SW version
          type: string
        type:
          $ref: '#/components/schemas/device_type'
        version:
          description: SW version running
          type: string
        version_description:
          description: Version description
          type: string
        version_eos_time:
          description: End of Service of version
          type: integer
        version_time:
          description: FRS date of the version
          type: integer
        warranty:
          description: warranty description
          type: string
        warranty_time:
          description: Time when warranty needs to be renewed
          type: integer
        warranty_type:
          $ref: '#/components/schemas/jsi_warranty_type'
      type: object
    jsi_warranty_type:
      description: "Warranty type for Juniper Support Insight (JSI) devices. The warranty type\nis used to determine the support level and duration of the warranty for the\ndevice. enum:\n  * WTY00001: Standard Hardware Warranty\n  * WTY00002: Enhanced Hardware Warranty\n  * WTY00003: Dead On Arrival Warranty\n  * WTY00004: Limited Lifetime Warranty\n  * WTY00005: Software Warranty\n  * WTY00006: Limited Lifetime Warranty for WLA\n  * WTY00007: Warranty-JCPO EOL (DOA Not Included)\n  * WTY00008: MIST Enhanced Hardware Warranty\n  * WTY00009: MIST Standard Warranty\n  * WTY00099: Determine Lifetime warranty\n"
      enum:
      - Standard Hardware Warranty
      - Enhanced Hardware Warranty
      - Dead On Arrival Warranty
      - Limited Lifetime Warranty
      - Software Warranty
      - Limited Lifetime Warranty for WLA
      - Warranty-JCPO EOL (DOA Not Included)
      - MIST Enhanced Hardware Warranty
      - MIST Standard Warranty
      - Determine Lifetime warranty
      type: string
  responses:
    JsiInventoryError:
      content:
        application/json:
          examples:
            No Juniper Account Linked:
              $ref: '#/components/examples/JsiInventoryErrorNoJuniperAccountLinked'
          schema:
            $ref: '#/components/schemas/response_detail_string'
        application/vnd.api+json:
          examples:
            No Juniper Account Linked:
              $ref: '#/components/examples/JsiInventoryErrorNoJuniperAccountLinked'
          schema:
            $ref: '#/components/schemas/response_detail_string'
      description: Bad Request - no Juniper Account Linked
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
      description: Unauthorized
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
      description: Bad Syntax
    JunosRegisterCmd:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/JunosRegisterCmdExample'
          schema:
            $ref: '#/components/schemas/response_device_config_cmd'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/JunosRegisterCmdExample'
          schema:
            $ref: '#/components/schemas/response_device_config_cmd'
      description: OK
    JsiDevices:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/JsiDevicesExample'
          schema:
            $ref: '#/components/schemas/jse_devices'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/JsiDevicesExample'
          schema:
            $ref: '#/components/schemas/jse_devices'
      description: OK
    HTTP404:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_http404'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_http404'
      description: Not found. The API endpoint doesn’t exist or resource doesn’ t exist
    WebsocketSessionWithUrl:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/websocket_session_with_url'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/websocket_session_with_url'
      description: OK
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
      description: Permission Denied
    JsiPbnSearch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jsi_pbn_search'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/jsi_pbn_search'
      description: OK
    JsiSirtSearch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jsi_sirt_search'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/jsi_sirt_search'
      description: OK
    JsiInventorySearch:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/JsiInventorySearchExample'
          schema:
            $ref: '#/components/schemas/js_inventory_search'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/JsiInventorySearchExample'
          schema:
            $ref: '#/components/schemas/js_inventory_search'
      description: OK
    JsiPbnCount:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_count'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_count'
      description: OK
    Count:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/CountExample'
          schema:
            $ref: '#/components/schemas/response_count'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/CountExample'
          schema:
            $ref: '#/components/schemas/response_count'
      description: Result of Count
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
      description: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    JsiSirtCount:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_count'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_count'
      description: OK
    JsiInventory:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/JsiInventoryExample'
          schema:
            $ref: '#/components/schemas/js_inventory'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/JsiInventoryExample'
          schema:
            $ref: '#/components/schemas/js_inventory'
      description: OK
  parameters:
    page:
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    start:
      description: Start time (epoch timestamp in seconds, or relative string like "-1d", "-1w")
      in: query
      name: start
      schema:
        type: string
    end:
      description: End time (epoch timestamp in seconds, or relative string like "-1d", "-2h", "now")
      in: query
      name: end
      schema:
        type: string
    sort:
      description: On which field the list should be sorted, -prefix represents DESC order
      in: query
      name: sort
      schema:
        default: timestamp
        examples:
        - -site_id
        type: string
    device_mac:
      in: path
      name: device_mac
      required: true
      schema:
        examples:
        - 0000000000ab
        pattern: ^[0-9a-fA-F]{12}$
        type: string
    org_id:
      in: path
      name: org_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    search_after:
      description: Pagination cursor for retrieving subsequent pages of results. This value is automatically populated by Mist in the `next` URL from the previous response and should not be manually constructed.
      in: query
      name: search_after
      schema:
        type: string
    limit:
      in: query
      name: limit
      schema:
        default: 100
        minimum: 0
        type: integer
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.
      scheme: basic
      type: http
    csrfToken:
      description: "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```"
      in: header
      name: X-CSRFToken
      type: apiKey
