openapi: 3.1.0
info:
  contact:
    email: tmunzer@juniper.net
    name: Thomas Munzer
  description: '> Version: **2604.1.1**

    >

    > Date: **May 13, 2026**

    <div class="notification"> NOTE:<br>Some important API changes will be introduced. Please make sure to read the <a href="https://www.juniper.net/documentation/us/en/software/mist/api/http/guides/important-api-changes">announcements</a> </div>


    ---

    ## Additional Documentation

    * [Mist Automation Guide](https://www.juniper.net/documentation/us/en/software/mist/automation-integration/index.html)

    * [Mist Location SDK](https://www.juniper.net/documentation/us/en/software/mist/location-services/topics/concept/mist-how-get-mist-sdk.html)

    * [Mist Product Updates](https://www.juniper.net/documentation/us/en/software/mist/product-updates/)


    ## Helpful Resources

    * [API Sandbox and Exercises](https://api-class.mist.com/)

    * [Postman Collection, Runners and Webhook Samples](https://www.postman.com/juniper-mist/workspace/mist-systems-s-public-workspace)

    * [Python Script Examples](https://github.com/tmunzer/mist_library)

    * [API Demo Apps](https://apps.mist-lab.fr/)

    * [Juniper Blog](https://blogs.juniper.net/)


    ## Mist Web Browser Extension:

    * Google Chrome, Microsoft Edge and other Chromium-based browser: [Chrome Web Store](https://chromewebstore.google.com/detail/mist-extension/ejhpdcljeamillfhdihkkmoakanpbplh)

    * Firefox: [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/mist-extension/)


    ---'
  license:
    name: MIT
    url: https://raw.githubusercontent.com/tmunzer/Mist-OAS3.0/main/LICENSE
  title: Mist Admins Sites Clients - Wireless API
  version: 2604.1.1
  x-logo:
    altText: Juniper-MistAI
    backgroundColor: '#FFFFFF'
    url: https://www.mist.com/wp-content/uploads/logo.png
servers:
- description: Mist Global 01
  url: https://api.mist.com
- description: Mist Global 02
  url: https://api.gc1.mist.com
- description: Mist Global 03
  url: https://api.ac2.mist.com
- description: Mist Global 04
  url: https://api.gc2.mist.com
- description: Mist Global 05
  url: https://api.gc4.mist.com
- description: Mist EMEA 01
  url: https://api.eu.mist.com
- description: Mist EMEA 02
  url: https://api.gc3.mist.com
- description: Mist EMEA 03
  url: https://api.ac6.mist.com
- description: Mist EMEA 04
  url: https://api.gc6.mist.com
- description: Mist APAC 01
  url: https://api.ac5.mist.com
- description: Mist APAC 02
  url: https://api.gc5.mist.com
- description: Mist APAC 03
  url: https://api.gc7.mist.com
security:
- apiToken: []
- basicAuth: []
- basicAuth: []
  csrfToken: []
tags:
- description: Wireless Clients are Wi-Fi devices connected to a Juniper Mist Access Point.
  name: Sites Clients - Wireless
paths:
  /api/v1/sites/{site_id}/clients/count:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Count by Distinct Attributes of Clients
      operationId: countSiteWirelessClients
      parameters:
      - example: hostname
        in: query
        name: distinct
        schema:
          $ref: '#/components/schemas/site_clients_count_distinct'
      - in: query
        name: ssid
        schema:
          type: string
      - in: query
        name: ap
        schema:
          type: string
      - $ref: '#/components/parameters/ip'
      - in: query
        name: vlan
        schema:
          type: string
      - in: query
        name: hostname
        schema:
          type: string
      - in: query
        name: os
        schema:
          type: string
      - in: query
        name: model
        schema:
          type: string
      - in: query
        name: device
        schema:
          type: string
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          $ref: '#/components/responses/Count'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countSiteWirelessClients
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/events/count:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Count by Distinct Attributes of Client-Events
      operationId: countSiteWirelessClientEvents
      parameters:
      - example: type
        in: query
        name: distinct
        schema:
          $ref: '#/components/schemas/site_client_events_count_distinct'
      - $ref: '#/components/parameters/client_event_type'
      - description: For assoc/disassoc events
        in: query
        name: reason_code
        schema:
          type: integer
      - description: SSID Name
        in: query
        name: ssid
        schema:
          type: string
      - description: AP MAC
        in: query
        name: ap
        schema:
          type: string
      - $ref: '#/components/parameters/dot11_proto'
      - $ref: '#/components/parameters/dot11_band'
      - description: WLAN_id
        in: query
        name: wlan_id
        schema:
          type: string
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          $ref: '#/components/responses/Count'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countSiteWirelessClientEvents
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/events/search:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Get Site Clients Events
      operationId: searchSiteWirelessClientEvents
      parameters:
      - $ref: '#/components/parameters/client_event_type'
      - description: For assoc/disassoc events
        in: query
        name: reason_code
        schema:
          type: integer
      - description: SSID Name
        in: query
        name: ssid
        schema:
          type: string
      - description: AP MAC
        in: query
        name: ap
        schema:
          type: string
      - $ref: '#/components/parameters/dot11_proto'
      - $ref: '#/components/parameters/dot11_band'
      - description: WLAN_id
        in: query
        name: wlan_id
        schema:
          type: string
      - description: nacrule_id
        in: query
        name: nacrule_id
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search_after'
      responses:
        '200':
          $ref: '#/components/responses/EventsSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchSiteWirelessClientEvents
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/search:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: 'Search Wireless Clients


        **NOTE**: fuzzy logic can be used with ‘*’, supported filters: mac, hostname, device, os, model. E.g. /clients/search?device=Mac*&hostname=jerry'
      operationId: searchSiteWirelessClients
      parameters:
      - description: AP MAC address of the AP where the client has connected to
        in: query
        name: ap
        schema:
          examples:
          - 5c5b53010101
          type: string
      - description: 'Comma separated list of Radio band (e.g. `24,5`). enum: `24`, `5`, `6`'
        in: query
        name: band
        schema:
          examples:
          - '5'
          type: string
      - description: Comma separated list of Device type (e.g. `Mac,iPhone`). Case sensitive
        in: query
        name: device
        schema:
          examples:
          - iPhone
          type: string
      - $ref: '#/components/parameters/partial_filter_hostname_client'
      - $ref: '#/components/parameters/partial_filter_ip_client'
      - $ref: '#/components/parameters/partial_filter_mac_client'
      - description: Only available for clients running the Marvis Client app, model, e.g. "MBP 15 late 2013", 6, 6s, "8+ GSM"
        in: query
        name: model
        schema:
          examples:
          - iPhone 8
          type: string
      - description: Only available for clients running the Marvis Client app, os, e.g. Sierra, Yosemite, Windows 10
        in: query
        name: os
        schema:
          examples:
          - Windows 10
          type: string
      - $ref: '#/components/parameters/psk_id_query'
      - description: Only available for clients using PPSK authentication, the Name of the PSK
        in: query
        name: psk_name
        schema:
          examples:
          - MyPPSK
          type: string
      - description: SSID
        in: query
        name: ssid
        schema:
          examples:
          - MySSID
          type: string
      - description: Partial / full MAC address, hostname, username, psk_name or ip. Use `prefix*` for prefix search or `*substring*` for contains search (e.g. `everest*` and `*rest*` match `my-everest-client`). Suffix-only wildcards (e.g. `*client`) are not supported
        in: query
        name: text
        schema:
          examples:
          - 5c5b530
          type: string
      - $ref: '#/components/parameters/partial_search_username'
      - description: VLAN
        in: query
        name: vlan
        schema:
          examples:
          - '10'
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search_after'
      responses:
        '200':
          $ref: '#/components/responses/ClientsSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchSiteWirelessClients
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/sessions/count:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Count by Distinct Attributes of Client Sessions
      operationId: countSiteWirelessClientSessions
      parameters:
      - in: query
        name: distinct
        schema:
          $ref: '#/components/schemas/site_client_sessions_count_distinct'
      - description: AP MAC
        in: query
        name: ap
        schema:
          type: string
      - $ref: '#/components/parameters/dot11_band'
      - description: E.g. "Mac", "iPhone", "Apple watch"
        in: query
        name: client_family
        schema:
          type: string
      - description: E.g. "Apple"
        in: query
        name: client_manufacture
        schema:
          type: string
      - description: E.g. "8+", "XS"
        in: query
        name: client_model
        schema:
          type: string
      - description: E.g. "Mojave", "Windows 10", "Linux"
        in: query
        name: client_os
        schema:
          type: string
      - description: SSID
        in: query
        name: ssid
        schema:
          type: string
      - description: WLAN_id
        in: query
        name: wlan_id
        schema:
          type: string
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          $ref: '#/components/responses/Count'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: countSiteWirelessClientSessions
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/sessions/search:
    parameters:
    - $ref: '#/components/parameters/site_id'
    get:
      description: Search Client Sessions
      operationId: searchSiteWirelessClientSessions
      parameters:
      - description: AP MAC
        in: query
        name: ap
        schema:
          type: string
      - $ref: '#/components/parameters/dot11_band'
      - description: E.g. "Mac", "iPhone", "Apple watch"
        in: query
        name: client_family
        schema:
          type: string
      - description: E.g. "Apple"
        in: query
        name: client_manufacture
        schema:
          type: string
      - description: E.g. "8+", "XS"
        in: query
        name: client_model
        schema:
          type: string
      - description: Username
        in: query
        name: client_username
        schema:
          type: string
      - description: E.g. "Mojave", "Windows 10", "Linux"
        in: query
        name: client_os
        schema:
          type: string
      - description: SSID
        in: query
        name: ssid
        schema:
          type: string
      - description: WLAN_id
        in: query
        name: wlan_id
        schema:
          type: string
      - $ref: '#/components/parameters/psk_id_query'
      - description: PSK Name
        in: query
        name: psk_name
        schema:
          type: string
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search_after'
      responses:
        '200':
          $ref: '#/components/responses/ClientSessionsSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: searchSiteWirelessClientSessions
      tags:
      - Sites Clients - Wireless
  /api/v1/sites/{site_id}/clients/{client_mac}/events:
    parameters:
    - $ref: '#/components/parameters/site_id'
    - $ref: '#/components/parameters/client_mac'
    get:
      description: Get the list of events for a specific client
      operationId: getSiteEventsForClient
      parameters:
      - description: E.g. MARVIS_EVENT_CLIENT_DHCP_STUCK
        in: query
        name: type
        schema:
          type: string
      - $ref: '#/components/parameters/dot11_proto'
      - $ref: '#/components/parameters/dot11_band'
      - in: query
        name: channel
        schema:
          type: string
      - in: query
        name: wlan_id
        schema:
          type: string
      - in: query
        name: ssid
        schema:
          type: string
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/duration'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/page'
      responses:
        '200':
          $ref: '#/components/responses/ClientEventsSearch'
        '400':
          $ref: '#/components/responses/HTTP400'
        '401':
          $ref: '#/components/responses/HTTP401'
        '403':
          $ref: '#/components/responses/HTTP403'
        '404':
          $ref: '#/components/responses/HTTP404'
        '429':
          $ref: '#/components/responses/HTTP429'
      summary: getSiteEventsForClient
      tags:
      - Sites Clients - Wireless
components:
  parameters:
    ip:
      in: query
      name: ip
      schema:
        examples:
        - 192.168.1.1
        format: ipv4
        type: string
    dot11_proto:
      description: a / b / g / n / ac / ax
      in: query
      name: proto
      schema:
        $ref: '#/components/schemas/dot11_proto'
    duration:
      description: Duration like 7d, 2w
      in: query
      name: duration
      schema:
        default: 1d
        examples:
        - 10m
        type: string
    end:
      description: End time (epoch timestamp in seconds, or relative string like "-1d", "-2h", "now")
      in: query
      name: end
      schema:
        type: string
    partial_search_username:
      description: Partial / full username. Use `prefix*` for prefix search or `*substring*` for contains search (e.g. `johndoe*` and `*mycorp*` match `johndoe@mycorp.com`). Suffix-only wildcards (e.g. `*mycorp.com`) are not supported
      in: query
      name: username
      schema:
        examples:
        - johndoe
        - johnd*
        - '*ohnd*'
        type: string
    partial_filter_ip_client:
      description: Partial / full Client IP Address. Use `prefix*` for prefix search or `*substring*` for contains search (e.g. `10.100.10.*` and `*100.10.*` match `10.100.10.54`). Suffix-only wildcards (e.g. `*.54`) are not supported
      in: query
      name: ip
      schema:
        examples:
        - 10.100.10.54
        - 10.100.10.*
        - '*100.10.*'
        type: string
    partial_filter_mac_client:
      description: Partial / full Client MAC Address. Use `prefix*` for prefix search or `*substring*` for contains search (e.g. `aabbcc*` and `*bbcc*` match `aabbccddeeff`). Suffix-only wildcards (e.g. `*bccddeeff`) are not supported
      in: query
      name: mac
      schema:
        examples:
        - aabbccddeeff
        - aabbcc*
        - '*bbcc*'
        type: string
    search_after:
      description: Pagination cursor for retrieving subsequent pages of results. This value is automatically populated by Mist in the `next` URL from the previous response and should not be manually constructed.
      in: query
      name: search_after
      schema:
        type: string
    client_event_type:
      description: See [List Device Events Definitions](/#operations/listDeviceEventsDefinitions)
      in: query
      name: type
      schema:
        type: string
    page:
      in: query
      name: page
      schema:
        default: 1
        minimum: 1
        type: integer
    site_id:
      in: path
      name: site_id
      required: true
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        format: uuid
        type: string
    psk_id_query:
      description: PSK ID
      in: query
      name: psk_id
      schema:
        examples:
        - 000000ab-00ab-00ab-00ab-0000000000ab
        type: string
    start:
      description: Start time (epoch timestamp in seconds, or relative string like "-1d", "-1w")
      in: query
      name: start
      schema:
        type: string
    partial_filter_hostname_client:
      description: Partial / full Client hostname. Use `prefix*` for prefix search or `*substring*` for contains search (e.g. `everest*` and `*rest*` match `my-everest-client`). Suffix-only wildcards (e.g. `*everest`) are not supported
      in: query
      name: hostname
      schema:
        examples:
        - my-everest-client
        - my-everest*
        - '*everest*'
        type: string
    limit:
      in: query
      name: limit
      schema:
        default: 100
        minimum: 0
        type: integer
    sort:
      description: On which field the list should be sorted, -prefix represents DESC order
      in: query
      name: sort
      schema:
        default: timestamp
        examples:
        - -site_id
        type: string
    client_mac:
      in: path
      name: client_mac
      required: true
      schema:
        examples:
        - 0000000000ab
        pattern: ^[0-9a-fA-F]{12}$
        type: string
    dot11_band:
      description: 802.11 Band
      in: query
      name: band
      schema:
        $ref: '#/components/schemas/dot11_band'
  schemas:
    events_client:
      additionalProperties: false
      description: Client events
      properties:
        ap:
          type: string
        band:
          $ref: '#/components/schemas/dot11_band'
        bssid:
          type: string
        channel:
          type: integer
        key_mgmt:
          $ref: '#/components/schemas/client_key_mgmt'
        proto:
          $ref: '#/components/schemas/dot11_proto'
        ssid:
          type: string
        text:
          type: string
        timestamp:
          $ref: '#/components/schemas/timestamp'
        type:
          description: Event type, e.g. MARVIS_EVENT_CLIENT_FBT_FAILURE
          type: string
        type_code:
          description: For assoc/disassoc events
          type: integer
        wlan_id:
          format: uuid
          type: string
      required:
      - timestamp
      - band
      type: object
    response_client_sessions_search_results:
      items:
        $ref: '#/components/schemas/response_client_sessions_search_item'
      type: array
    client_wireless_ap:
      description: List of AP MAC Addresses the client was connected to
      examples:
      - - a83a79a947ee
        - 003e73170b4c
      items:
        type: string
      type: array
    dot11_proto:
      description: 'enum: `a`, `ac`, `ax`, `b`, `be`, `g`, `n`'
      enum:
      - a
      - ac
      - ax
      - b
      - be
      - g
      - n
      type: string
    client_wireless_os_version:
      description: Only when client is having the Marvis Client app running. List of OS version detected for the client
      examples:
      - - 14.4.1 (Build 23E224)
      items:
        type: string
      type: array
    site_client_events_count_distinct:
      description: 'enum: `band`, `channel`, `proto`, `ssid`, `type`, `wlan_id`'
      enum:
      - band
      - channel
      - proto
      - ssid
      - type
      - wlan_id
      type: string
    response_client_sessions_search:
      additionalProperties: false
      properties:
        end:
          type: integer
        limit:
          type: integer
        next:
          type: string
        results:
          $ref: '#/components/schemas/response_client_sessions_search_results'
        start:
          type: integer
        total:
          type: integer
      required:
      - end
      - limit
      - results
      - start
      - total
      type: object
    timestamp:
      description: Epoch (seconds)
      format: double
      readOnly: true
      type: number
    response_client_events_search:
      additionalProperties: false
      properties:
        end:
          type: integer
        limit:
          type: integer
        next:
          type: string
        results:
          $ref: '#/components/schemas/response_client_events_search_results'
        start:
          type: integer
        total:
          type: integer
      required:
      - start
      - end
      - limit
      - total
      - results
      type: object
    site_client_sessions_count_distinct:
      default: mac
      description: 'enum: `ap`, `client_family`, `client_manufacture`, `client_model`, `client_os`, `mac`, `ssid`, `wlan_id`'
      enum:
      - ap
      - client_family
      - client_manufacture
      - client_model
      - client_os
      - mac
      - ssid
      - wlan_id
      type: string
    client_wireless_ssid:
      description: List of the WLAN names the client was connected to
      examples:
      - - IoT SSID
      items:
        type: string
      type: array
    response_http401:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Authentication credentials were not provided.
          type: string
      type: object
    client_wireless_site_ids:
      description: List of Mist Site IDs where the client was connected
      examples:
      - - 25ff5219-9be7-4db9-907d-0c9b60445147
      items:
        format: uuid
        type: string
      type: array
    site_clients_count_distinct:
      default: device
      description: 'enum: `ap`, `device`, `hostname`, `ip`, `model`, `os`, `ssid`, `vlan`'
      enum:
      - ap
      - device
      - hostname
      - ip
      - model
      - os
      - ssid
      - vlan
      type: string
    response_count:
      additionalProperties: false
      properties:
        distinct:
          type: string
        end:
          type: integer
        limit:
          type: integer
        results:
          $ref: '#/components/schemas/count_results'
        start:
          type: integer
        total:
          type: integer
      required:
      - distinct
      - end
      - limit
      - results
      - start
      - total
      type: object
    last_username:
      description: If dot1x authentication, the username used during the latest authentication. Otherwise, the MAC address of the client
      examples:
      - john@mycorp.net
      type: string
    client_wireless_hostname:
      description: List of hostname detected for this client
      examples:
      - - hostname-a
        - hostname-b
      items:
        type: string
      type: array
    response_client_sessions_search_item:
      additionalProperties: false
      properties:
        ap:
          readOnly: true
          type: string
        band:
          readOnly: true
          type: string
        client_manufacture:
          readOnly: true
          type: string
        connect:
          readOnly: true
          type: number
        disconnect:
          readOnly: true
          type: number
        duration:
          readOnly: true
          type: number
        mac:
          readOnly: true
          type: string
        org_id:
          $ref: '#/components/schemas/org_id'
        site_id:
          $ref: '#/components/schemas/site_id'
        ssid:
          readOnly: true
          type: string
        tags:
          $ref: '#/components/schemas/response_client_sessions_search_item_tags'
        timestamp:
          $ref: '#/components/schemas/timestamp'
        wlan_id:
          format: uuid
          type: string
      required:
      - ap
      - band
      - client_manufacture
      - connect
      - disconnect
      - duration
      - mac
      - org_id
      - site_id
      - ssid
      - timestamp
      - wlan_id
      type: object
    last_client_ip:
      description: The last known IP Address for the client
      examples:
      - 10.100.0.157
      type: string
    response_client_events_search_results:
      items:
        $ref: '#/components/schemas/events_client'
      type: array
      uniqueItems: true
    response_client_sessions_search_item_tags:
      items:
        type: string
      readOnly: true
      type: array
    client_wireless:
      additionalProperties: false
      properties:
        ap:
          $ref: '#/components/schemas/client_wireless_ap'
        app_version:
          $ref: '#/components/schemas/client_wireless_app_version'
        band:
          description: Wi-Fi Radio band
          examples:
          - '5'
          type: string
        device:
          $ref: '#/components/schemas/client_wireless_device'
        ftc:
          type: boolean
        hardware:
          description: Only when client has the Marvis Client app running. Type of Wi-Fi adapter
          examples:
          - Apple Wi-Fi adapter
          type: string
        hostname:
          $ref: '#/components/schemas/client_wireless_hostname'
        ip:
          $ref: '#/components/schemas/client_wireless_ip'
        last_ap:
          $ref: '#/components/schemas/last_ap'
        last_device:
          $ref: '#/components/schemas/last_device'
        last_firmware:
          description: Only when client has the Marvis Client app running. Same as "firmware"
          examples:
          - 'wl0: Jan 20 2024 04:08:41 version 20.103.12.0.8.7.171 FWID 01-e09d2675'
          type: string
        last_hostname:
          description: Latest hostname we detected for the client
          examples:
          - hostname-a
          type: string
        last_ip:
          $ref: '#/components/schemas/last_client_ip'
        last_model:
          description: Only when client has the Marvis Client app running. latest client hardware model we detected for the client
          examples:
          - MBP 16\" M1 2021
          type: string
        last_os:
          description: Only when client has the Marvis Client app running. Latest version of OS Type we detected for the client
          examples:
          - Sonoma
          type: string
        last_os_version:
          description: Only when client has the Marvis Client app running. Latest version of OS Version we detected for the client
          examples:
          - 14.4.1 (Build 23E224)
          type: string
        last_psk_id:
          description: Only for PPSK authentication. Latest PPSK ID used by the client
          examples:
          - abf7dc5c-bb51-4bb7-93b6-5547400ffe11
          format: uuid
          type: string
        last_psk_name:
          description: Only for PPSK authentication. Latest PPSK Name used by the client
          examples:
          - iot
          type: string
        last_ssid:
          $ref: '#/components/schemas/last_username'
        last_username:
          type: string
        last_vlan:
          $ref: '#/components/schemas/last_vlan'
        last_wlan_id:
          description: ID of the latest SSID (WLAN) the client is/was connected to
          examples:
          - e5d67b07-aae8-494b-8584-cbc20c8110aa
          format: uuid
          type: string
        mac:
          description: Client MAC Address
          examples:
          - bcd074000000
          type: string
        mfg:
          description: Manufacturer of the client hardware (MAC OUI based)
          examples:
          - Apple
          type: string
        model:
          description: Only when client has the Marvis Client app running. Client hardware model
          examples:
          - MBP 16\" M1 2021
          type: string
        org_id:
          $ref: '#/components/schemas/org_id'
        os:
          $ref: '#/components/schemas/client_wireless_os'
        os_version:
          $ref: '#/components/schemas/client_wireless_os_version'
        protocol:
          description: 802.11 amendment
          examples:
          - ax
          type: string
        psk_id:
          $ref: '#/components/schemas/client_wireless_psk_id'
        psk_name:
          $ref: '#/components/schemas/client_wireless_psk_name'
        random_mac:
          description: Whether the client is using randomized MAC Address or not
          type: boolean
        sdk_version:
          $ref: '#/components/schemas/client_wireless_sdk_version'
        site_id:
          description: Mist Site ID where the client is connected
          examples:
          - 25ff5219-9be7-4db9-907d-0c9b60445147
          format: uuid
          type: string
        site_ids:
          $ref: '#/components/schemas/client_wireless_site_ids'
        ssid:
          $ref: '#/components/schemas/client_wireless_ssid'
        timestamp:
          $ref: '#/components/schemas/timestamp'
        username:
          $ref: '#/components/schemas/client_wireless_username'
        vlan:
          $ref: '#/components/schemas/client_wireless_vlan'
        wlan_id:
          $ref: '#/components/schemas/client_wireless_wlan_id'
      type: object
    client_wireless_vlan:
      description: List of vlans that have been assigned to the client
      examples:
      - - 10
      items:
        type: integer
      type: array
    response_client_search_results:
      items:
        $ref: '#/components/schemas/client_wireless'
      type: array
      uniqueItems: true
    response_events_search_results:
      items:
        $ref: '#/components/schemas/events_client'
      type: array
      uniqueItems: true
    count_result:
      additionalProperties:
        type: string
      properties:
        count:
          type: integer
      required:
      - count
      type: object
    last_vlan:
      description: Latest VLAN ID assigned to the client
      examples:
      - 10
      type: integer
    client_wireless_sdk_version:
      description: Only when client has the Marvis Client app running. List of Marvis Client SDK version detected for the client
      examples:
      - - 0.100.3
      items:
        type: string
      type: array
    response_events_search:
      additionalProperties: false
      properties:
        end:
          type: integer
        limit:
          type: integer
        next:
          type: string
        results:
          $ref: '#/components/schemas/response_events_search_results'
        start:
          type: integer
        total:
          type: integer
      required:
      - start
      - end
      - limit
      - total
      - results
      type: object
    last_device:
      description: Latest type of device we identified (e.g. iPhone, Mac, ...)
      examples:
      - Zebra
      type: string
    response_http429:
      additionalProperties: false
      properties:
        detail:
          examples:
          - Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
          type: string
      type: object
    client_wireless_device:
      description: Only when client has the Marvis Client app running. List of the type of device type detected
      examples:
      - - Mac
      items:
        type: string
      type: array
    client_key_mgmt:
      description: 'Key management protocol used for the latest authentication. enum: `WPA2-PSK`, `WPA2-PSK-FT`, `WPA2-PSK-SHA256`, `WPA3-EAP-SHA256`, `WPA3-SAE-FT`, `WPA3-SAE-PSK`'
      enum:
      - WPA2-PSK
      - WPA2-PSK/CCMP
      - WPA2-PSK-FT
      - WPA2-PSK-SHA256
      - WPA3-EAP-SHA256
      - WPA3-EAP-SHA256/CCMP
      - WPA3-EAP-FT/GCMP256
      - WPA3-SAE-FT
      - WPA3-SAE-PSK
      examples:
      - WPA2-PSK
      type: string
    org_id:
      examples:
      - a97c1b22-a4e9-411e-9bfd-d8695a0f9e61
      format: uuid
      readOnly: true
      type: string
    client_wireless_psk_id:
      description: List of IDs of the PPSK used by the client
      examples:
      - - abf7dc5c-bb51-4bb7-93b6-5547400ffe11
      items:
        format: uuid
        type: string
      type: array
    client_wireless_ip:
      description: List if the ip addresses detected for this client
      examples:
      - - 10.5.23.43
        - 192.168.0.2
      items:
        type: string
      type: array
    last_ap:
      description: Latest AP where the client is/was connected to
      examples:
      - a83a79a947ee
      type: string
    client_wireless_username:
      description: Only for 802.1X authentication. List of usernames used by the client
      examples:
      - - user@corp.com
      items:
        type: string
      type: array
    response_http403:
      additionalProperties: false
      properties:
        detail:
          examples:
          - You do not have permission to perform this action.
          type: string
      type: object
    client_wireless_psk_name:
      description: List of names of the PPSK used by the client
      examples:
      - - iot
      items:
        type: string
      type: array
    count_results:
      items:
        $ref: '#/components/schemas/count_result'
      type: array
      uniqueItems: true
    response_client_search:
      additionalProperties: false
      properties:
        end:
          type: number
        limit:
          type: integer
        next:
          type: string
        results:
          $ref: '#/components/schemas/response_client_search_results'
        start:
          type: number
        total:
          type: integer
      required:
      - start
      - end
      - limit
      - total
      - results
      type: object
    site_id:
      examples:
      - 441a1214-6928-442a-8e92-e1d34b8ec6a6
      format: uuid
      readOnly: true
      type: string
    response_http404:
      additionalProperties: false
      properties:
        id:
          type: string
      type: object
    client_wireless_os:
      description: Only when client is having the Marvis Client app running. List of OS detected for the client
      examples:
      - - Sonoma
      items:
        type: string
      type: array
    response_http400:
      additionalProperties: false
      properties:
        detail:
          examples:
          - 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
          type: string
      type: object
    client_wireless_app_version:
      description: Only when client has the Marvis Client app running. List of the versions of the Marvis Client
      examples:
      - - 0.100.3
      items:
        type: string
      type: array
    client_wireless_wlan_id:
      description: List of IDs of WLANs the client was connected to
      examples:
      - - e5d67b07-aae8-494b-8584-cbc20c8110aa
      items:
        format: uuid
        type: string
      type: array
    dot11_band:
      description: 'enum: `24`, `5`, `5-dedicated`, `5-selectable`, `6`, `6-dedicated`, `6-selectable`'
      enum:
      - '24'
      - '5'
      - 5-dedicated
      - 5-selectable
      - '6'
      - 6-dedicated
      - 6-selectable
      type: string
  responses:
    EventsSearch:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/EventsSearchExample'
          schema:
            $ref: '#/components/schemas/response_events_search'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/EventsSearchExample'
          schema:
            $ref: '#/components/schemas/response_events_search'
      description: OK
    HTTP403:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP403Example'
          schema:
            $ref: '#/components/schemas/response_http403'
      description: Permission Denied
    HTTP401:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP401Example'
          schema:
            $ref: '#/components/schemas/response_http401'
      description: Unauthorized
    ClientEventsSearch:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/ClientEventsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_events_search'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/ClientEventsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_events_search'
      description: OK
    ClientsSearch:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/ClientsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_search'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/ClientsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_search'
      description: OK
    HTTP404:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response_http404'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/response_http404'
      description: Not found. The API endpoint doesn’t exist or resource doesn’ t exist
    HTTP429:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP429Example'
          schema:
            $ref: '#/components/schemas/response_http429'
      description: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    ClientSessionsSearch:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/ClientSessionsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_sessions_search'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/ClientSessionsSearchExample'
          schema:
            $ref: '#/components/schemas/response_client_sessions_search'
      description: OK
    HTTP400:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/HTTP400Example'
          schema:
            $ref: '#/components/schemas/response_http400'
      description: Bad Syntax
    Count:
      content:
        application/json:
          examples:
            Example:
              $ref: '#/components/examples/CountExample'
          schema:
            $ref: '#/components/schemas/response_count'
        application/vnd.api+json:
          examples:
            Example:
              $ref: '#/components/examples/CountExample'
          schema:
            $ref: '#/components/schemas/response_count'
      description: Result of Count
  examples:
    HTTP403Example:
      value:
        detail: You do not have permission to perform this action.
    ClientSessionsSearchExample:
      value:
        end: 1513177200
        limit: 10
        results:
        - ap: 5c5b350e0262
          band: '5'
          client_manufacture: Apple
          connect: 1565208388
          disconnect: 1565208448
          duration: 60.09423865
          mac: b019c66c8348
          org_id: 3139f2c2-fac6-11e5-8156-0242ac110006
          site_id: 70e0f468-fc13-11e5-85ad-0242ac110008
          ssid: Dummy WLAN 2
          tags:
          - disassociate
          timestamp: 1565208448.662
          wlan_id: 99bb4c74-f954-4f36-b844-6b030faffabc
        start: 1511967600
        total: 100
    CountExample:
      value:
        distinct: string
        end: 0
        limit: 0
        results:
        - count: 0
          property: string
        start: 0
        total: 0
    ClientsSearchExample:
      value:
        end: 17141231418.812
        limit: 118
        next: next8
        results:
        - ap:
          - a83a79a947ee
          - 003e73170b4c
          app_version:
          - 0.100.3
          band: '5'
          device:
          - Mac
          ftc: false
          hardware: Apple Wi-Fi adapter
          hostname:
          - hostname-a
          - hostname-b
          ip:
          - 10.5.23.43
          - 192.168.0.2
          last_ap: a83a79a947ee
          last_device: Mac
          last_firmware: 'wl0: Jan 20 2024 04:08:41 version 20.103.12.0.8.7.171 FWID 01-e09d2675'
          last_hostname: hostname-a
          last_ip: 10.5.23.43
          last_model: MBP 16\" M1 2021
          last_os: Sonoma
          last_os_version: 14.4.1 (Build 23E224)
          last_psk_id: abf7dc5c-bb51-4bb7-93b6-5547400ffe11
          last_psk_name: iot
          last_ssid: IoT SSID
          last_username: user@corp.com
          last_vlan: 10
          last_wlan_id: e5d67b07-aae8-494b-8584-cbc20c8110aa
          mac: bcd074000000
          mfg: Apple
          model: MBP 16\" M1 2021
          org_id: 1abff1aa-4571-4c1f-a409-153a1e7a7a24
          os:
          - Sonoma
          os_version:
          - 14.4.1 (Build 23E224)
          protocol: ax
          psk_id:
          - abf7dc5c-bb51-4bb7-93b6-5547400ffe11
          psk_name:
          - iot
          sdk_version:
          - 0.100.3
          site_id: 25ff5219-9be7-4db9-907d-0c9b60445147
          site_ids:
          - 25ff5219-9be7-4db9-907d-0c9b60445147
          ssid:
          - IoT SSID
          timestamp: 1714124722.113
          username:
          - user@corp.com
          vlan:
          - 10
        start: 10
        total: 44
    HTTP429Example:
      value:
        detail: Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold
    ClientEventsSearchExample:
      value:
        end: 1513176951
        limit: 10
        results:
        - ap: 5c5b350eb31b
          band: '5'
          bssid: 5c5b350918f1
          channel: 149
          proto: ac
          ssid: Guest
          text: Status code 0 "Successful"
          timestamp: 1513358874.667
          type: CLIENT_DNS_OK
          type_code: 15
          wlan_id: be22bba7-8e22-e1cf-5185-b880816fe2cf
        start: 1512572151
        total: 1
    EventsSearchExample:
      value:
        end: 0
        limit: 0
        results:
        - ap: string
          band: '24'
          bssid: string
          channel: 0
          proto: a
          ssid: string
          text: string
          timestamp: 0
          type: string
          type_code: 0
          wlan_id: b069b358-4c97-5319-1f8c-7c5ca64d6ab1
        start: 0
        total: 0
    HTTP400Example:
      value:
        detail: 'JSON parse error - Expecting value: line 5 column 8 (char 56)'
    HTTP401Example:
      value:
        detail: Authentication credentials were not provided.
  securitySchemes:
    apiToken:
      description: "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information."
      in: header
      name: Authorization
      type: apiKey
    basicAuth:
      description: While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.
      scheme: basic
      type: http
    csrfToken:
      description: "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```"
      in: header
      name: X-CSRFToken
      type: apiKey
